import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import { connectDB, disconnectDB } from '../config/db';
import { User } from '../models/User';
import { LandRecord } from '../models/LandRecord';
import { DocumentModel, ValidationResultModel, VerificationTaskModel, AuditLogModel } from '../models/DocumentAndAudit';
import { validationEngine } from '../services/validation/ValidationEngine';
import { ExtractedField, LandClassification, OwnershipType } from '../../../shared/types';

function createField<T>(
  val: T,
  conf = 0.95,
  src: 'OCR' | 'AI_EXTRACTION' | 'RULE_DERIVED' | 'HUMAN_VERIFIED' = 'OCR',
  box?: any
): ExtractedField<T> {
  return {
    value: val,
    confidence: conf,
    source: src,
    boundingBox: box || { x: 15, y: 25, width: 30, height: 4, page: 1 },
    isVerified: src === 'HUMAN_VERIFIED',
    originalValue: val,
    rawOcrText: String(val),
  };
}

export async function seedDatabase() {
  console.log('🌱 Starting Bhoomi Setu AI Database Seed...');

  // Drop database to reset indexes and clean seed
  try {
    await mongoose.connection.dropDatabase();
  } catch (err) {
    console.log('Drop db info:', err);
  }

  // 1. Seed Users
  const passwordHash = await bcrypt.hash('Bhoomi@2026', 10);
  const users = [
    {
      name: 'Dr. Rajeshwar Verma, IAS',
      email: 'admin@bhoomi.gov.in',
      passwordHash,
      role: 'admin',
      department: 'Revenue & Land Reforms Department',
      district: 'Sehore',
      state: 'Madhya Pradesh',
    },
    {
      name: 'Smt. Priya Sharma',
      email: 'district@bhoomi.gov.in',
      passwordHash,
      role: 'district_officer',
      department: 'Office of District Collector, Sehore',
      district: 'Sehore',
      state: 'Madhya Pradesh',
    },
    {
      name: 'Shri Manoj Patel',
      email: 'officer@bhoomi.gov.in',
      passwordHash,
      role: 'verification_officer',
      department: 'Tehsil Revenue Office, Sehore',
      district: 'Sehore',
      state: 'Madhya Pradesh',
    },
    {
      name: 'Ananya Deshmukh',
      email: 'viewer@bhoomi.gov.in',
      passwordHash,
      role: 'viewer',
      department: 'Public Land Records Portal',
      district: 'Bhopal',
      state: 'Madhya Pradesh',
    },
  ];

  const createdUsers = await User.insertMany(users);
  console.log(` Created ${createdUsers.length} system users.`);

  // 2. Prepare 20 Realistic Land Records with specific test scenarios
  const recordsData = [
    // Scenario 1: Baseline Clean Record
    {
      recordId: 'REC-MP-SEH-001',
      documentId: 'DOC-MP-2026-001',
      ownerName: createField('रमेश कुमार (Ramesh Kumar)', 0.96, 'OCR', { x: 12, y: 22, width: 38, height: 4, page: 1 }),
      fatherOrSpouseName: createField('सुरेश कुमार (Suresh Kumar)', 0.94),
      surveyNumber: createField('124/3', 0.98, 'OCR', { x: 12, y: 30, width: 25, height: 4, page: 1 }),
      khasraNumber: createField('124/3', 0.98),
      khataNumber: createField('458', 0.93),
      plotNumber: createField('P-124', 0.90),
      area: createField(2.45, 0.92, 'OCR', { x: 12, y: 38, width: 25, height: 4, page: 1 }),
      areaUnit: createField('Acres', 0.95),
      village: createField('Rampur', 0.97),
      tehsil: createField('Sehore', 0.96),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.95),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.92),
      mutationNumber: createField('M-2023-1102', 0.94),
      registrationNumber: createField('REG-2022-8921', 0.91),
      registrationDate: createField('2022-08-15', 0.93),
      mutationDate: createField('2023-03-14', 0.92),
      language: 'Hindi',
      confidenceScore: 94,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.2045, lng: 77.0862 },
    },

    // Scenario 2: Ownership Conflict (Same Survey 124/3 with different owner "दिनेश चंद्र / Dinesh Chandra")
    {
      recordId: 'REC-MP-SEH-002',
      documentId: 'DOC-MP-2026-002',
      ownerName: createField('दिनेश चंद्र (Dinesh Chandra)', 0.92, 'OCR', { x: 12, y: 22, width: 36, height: 4, page: 1 }),
      fatherOrSpouseName: createField('रामप्रसाद (Ramprasad)', 0.91),
      surveyNumber: createField('124/3', 0.95, 'OCR', { x: 12, y: 30, width: 25, height: 4, page: 1 }),
      khasraNumber: createField('124/3', 0.95),
      khataNumber: createField('912', 0.88),
      area: createField(2.45, 0.91),
      areaUnit: createField('Acres', 0.95),
      village: createField('Rampur', 0.97),
      tehsil: createField('Sehore', 0.96),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.94),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.90),
      mutationNumber: createField('M-2024-0041', 0.89),
      registrationNumber: createField('REG-2024-1109', 0.88),
      registrationDate: createField('2024-01-10', 0.91),
      mutationDate: createField('2024-02-18', 0.90),
      language: 'Hindi',
      confidenceScore: 88,
      validationStatus: 'failed',
      verificationStatus: 'pending',
      gisCoordinates: { lat: 23.2046, lng: 77.0863 },
    },

    // Scenario 3: Parent Parcel (Survey 88 - 5.00 Acres)
    {
      recordId: 'REC-MP-SEH-003',
      documentId: 'DOC-MP-2026-003',
      ownerName: createField('गोपाल दास (Gopal Das)', 0.95),
      fatherOrSpouseName: createField('हरिराम (Hariram)', 0.94),
      surveyNumber: createField('88', 0.97),
      khasraNumber: createField('88', 0.97),
      khataNumber: createField('114', 0.92),
      area: createField(5.00, 0.95),
      areaUnit: createField('Acres', 0.95),
      village: createField('Rampur', 0.97),
      tehsil: createField('Sehore', 0.96),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.95),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.93),
      mutationNumber: createField('M-2019-3301', 0.90),
      registrationDate: createField('2019-04-10', 0.92),
      mutationDate: createField('2019-06-22', 0.91),
      language: 'Hindi',
      confidenceScore: 95,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.2110, lng: 77.0915 },
    },

    // Scenario 4: Sub-parcel 88/1 (3.20 Acres)
    {
      recordId: 'REC-MP-SEH-004',
      documentId: 'DOC-MP-2026-004',
      ownerName: createField('सुनील दास (Sunil Das)', 0.93),
      fatherOrSpouseName: createField('गोपाल दास (Gopal Das)', 0.92),
      surveyNumber: createField('88/1', 0.96),
      khasraNumber: createField('88/1', 0.96),
      khataNumber: createField('114-A', 0.89),
      area: createField(3.20, 0.92),
      areaUnit: createField('Acres', 0.95),
      village: createField('Rampur', 0.97),
      tehsil: createField('Sehore', 0.96),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.95),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.90),
      parentSurveyNumber: '88',
      language: 'Hindi',
      confidenceScore: 92,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.2112, lng: 77.0917 },
    },

    // Scenario 5: Sub-parcel 88/2 (2.80 Acres) -> 3.20 + 2.80 = 6.00 Acres > Parent 5.00 Acres (Area Mismatch Violation!)
    {
      recordId: 'REC-MP-SEH-005',
      documentId: 'DOC-MP-2026-005',
      ownerName: createField('मुकेश दास (Mukesh Das)', 0.91),
      fatherOrSpouseName: createField('गोपाल दास (Gopal Das)', 0.90),
      surveyNumber: createField('88/2', 0.94),
      khasraNumber: createField('88/2', 0.94),
      khataNumber: createField('114-B', 0.88),
      area: createField(2.80, 0.90),
      areaUnit: createField('Acres', 0.95),
      village: createField('Rampur', 0.97),
      tehsil: createField('Sehore', 0.96),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.95),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.90),
      parentSurveyNumber: '88',
      language: 'Hindi',
      confidenceScore: 90,
      validationStatus: 'failed',
      verificationStatus: 'pending',
      gisCoordinates: { lat: 23.2114, lng: 77.0919 },
    },

    // Scenario 6: Chronological Date Anomaly (Mutation Date 2021-03-10 BEFORE Registration Date 2022-08-15)
    {
      recordId: 'REC-MP-SEH-006',
      documentId: 'DOC-MP-2026-006',
      ownerName: createField('महेंद्र सिंह (Mahendra Singh)', 0.94),
      fatherOrSpouseName: createField('विक्रम सिंह (Vikram Singh)', 0.92),
      surveyNumber: createField('302/1', 0.95),
      khasraNumber: createField('302/1', 0.95),
      khataNumber: createField('781', 0.90),
      area: createField(1.85, 0.91),
      areaUnit: createField('Acres', 0.95),
      village: createField('Bilkisganj', 0.96),
      tehsil: createField('Sehore', 0.95),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.94),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.92),
      registrationNumber: createField('REG-2022-4419', 0.89),
      registrationDate: createField('2022-08-15', 0.92),
      mutationNumber: createField('M-2021-9981', 0.88),
      mutationDate: createField('2021-03-10', 0.87), // Inverted date!
      language: 'Hindi',
      confidenceScore: 89,
      validationStatus: 'warning',
      verificationStatus: 'pending',
      gisCoordinates: { lat: 23.1890, lng: 77.1020 },
    },

    // Scenario 7: Low OCR Confidence / Noisy Scanned Document (<70% on critical fields)
    {
      recordId: 'REC-MP-SEH-007',
      documentId: 'DOC-MP-2026-007',
      ownerName: createField('कैलाश ना..थ (Kailash N..th)', 0.58, 'OCR', { x: 10, y: 22, width: 34, height: 4, page: 1 }),
      fatherOrSpouseName: createField('शंकर लाल (Shankar Lal)', 0.64),
      surveyNumber: createField('215/?', 0.61),
      khasraNumber: createField('215/?', 0.61),
      khataNumber: createField('339', 0.68),
      area: createField(3.40, 0.62),
      areaUnit: createField('Acres', 0.80),
      village: createField('Shyampur', 0.92),
      tehsil: createField('Sehore', 0.95),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.88),
      ownershipType: createField<OwnershipType>('Joint Ownership (संयुक्त)', 0.75),
      language: 'Hindi',
      confidenceScore: 64,
      validationStatus: 'warning',
      verificationStatus: 'pending',
      gisCoordinates: { lat: 23.2450, lng: 77.0620 },
    },

    // Additional 13 clean / diverse state & district records
    {
      recordId: 'REC-MP-BHP-008',
      documentId: 'DOC-MP-2026-008',
      ownerName: createField('Anita Deshmukh', 0.98),
      fatherOrSpouseName: createField('Pramod Deshmukh', 0.96),
      surveyNumber: createField('45/1A', 0.97),
      khasraNumber: createField('45/1A', 0.97),
      khataNumber: createField('1024', 0.95),
      area: createField(0.45, 0.96),
      areaUnit: createField('Acres', 0.98),
      village: createField('Kolar', 0.98),
      tehsil: createField('Huzur', 0.97),
      district: createField('Bhopal', 0.99),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Residential (आवासीय)', 0.97),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.96),
      language: 'English',
      confidenceScore: 97,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.1850, lng: 77.4200 },
    },
    {
      recordId: 'REC-MP-BHP-009',
      documentId: 'DOC-MP-2026-009',
      ownerName: createField('सत्यनारायण शर्मा (Satyanarayan Sharma)', 0.96),
      fatherOrSpouseName: createField('द्वारका प्रसाद (Dwarka Prasad)', 0.95),
      surveyNumber: createField('712', 0.97),
      khasraNumber: createField('712', 0.97),
      khataNumber: createField('550', 0.94),
      area: createField(4.20, 0.95),
      areaUnit: createField('Acres', 0.96),
      village: createField('Ratibad', 0.97),
      tehsil: createField('Huzur', 0.97),
      district: createField('Bhopal', 0.99),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.96),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.95),
      language: 'Hindi',
      confidenceScore: 96,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.1420, lng: 77.3180 },
    },
    {
      recordId: 'REC-MP-VID-010',
      documentId: 'DOC-MP-2026-010',
      ownerName: createField('भागवत प्रसाद (Bhagwat Prasad)', 0.94),
      fatherOrSpouseName: createField('चतुर्भुज (Chaturbhuj)', 0.92),
      surveyNumber: createField('108/2', 0.96),
      khasraNumber: createField('108/2', 0.96),
      khataNumber: createField('219', 0.91),
      area: createField(1.60, 0.93),
      areaUnit: createField('Acres', 0.95),
      village: createField('Gulabganj', 0.96),
      tehsil: createField('Vidisha', 0.96),
      district: createField('Vidisha', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.95),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.92),
      language: 'Hindi',
      confidenceScore: 94,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.6120, lng: 77.8920 },
    },
    {
      recordId: 'REC-MP-IND-011',
      documentId: 'DOC-MP-2026-011',
      ownerName: createField('Vijay Industrial Parks Pvt Ltd', 0.97),
      fatherOrSpouseName: createField('Director: Anand R.', 0.95),
      surveyNumber: createField('504/1', 0.98),
      khasraNumber: createField('504/1', 0.98),
      khataNumber: createField('882', 0.96),
      area: createField(8.50, 0.96),
      areaUnit: createField('Acres', 0.98),
      village: createField('Palda', 0.98),
      tehsil: createField('Indore', 0.98),
      district: createField('Indore', 0.99),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Industrial (औद्योगिक)', 0.97),
      ownershipType: createField<OwnershipType>('Trust / Institutional (संस्थागत)', 0.96),
      language: 'English',
      confidenceScore: 97,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 22.6820, lng: 75.8920 },
    },
    {
      recordId: 'REC-MH-PUN-012',
      documentId: 'DOC-MH-2026-012',
      ownerName: createField('तानाजी भोसले (Tanaji Bhosle)', 0.95),
      fatherOrSpouseName: createField('संभाजी भोसले (Sambhaji Bhosle)', 0.94),
      surveyNumber: createField('240/1A', 0.96),
      khasraNumber: createField('240/1A', 0.96),
      khataNumber: createField('670', 0.92),
      area: createField(3.10, 0.94),
      areaUnit: createField('Acres', 0.95),
      village: createField('Wagholi', 0.96),
      tehsil: createField('Haveli', 0.96),
      district: createField('Pune', 0.99),
      state: createField('Maharashtra', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.95),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.94),
      language: 'Marathi',
      confidenceScore: 95,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 18.5780, lng: 73.9810 },
    },
    {
      recordId: 'REC-MP-SEH-013',
      ownerName: createField('कमल सिंह (Kamal Singh)', 0.93),
      fatherOrSpouseName: createField('भंवर सिंह (Bhanwar Singh)', 0.91),
      surveyNumber: createField('410/2', 0.95),
      khasraNumber: createField('410/2', 0.95),
      khataNumber: createField('310', 0.90),
      area: createField(2.10, 0.92),
      areaUnit: createField('Acres', 0.95),
      village: createField('Doraha', 0.95),
      tehsil: createField('Sehore', 0.96),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.94),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.91),
      language: 'Hindi',
      confidenceScore: 93,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.2890, lng: 77.1420 },
    },
    {
      recordId: 'REC-MP-SEH-014',
      ownerName: createField('विष्णुकांत तिवारी (Vishnukant Tiwari)', 0.95),
      fatherOrSpouseName: createField('देवकीनंदन (Devkinandan)', 0.93),
      surveyNumber: createField('502', 0.97),
      khasraNumber: createField('502', 0.97),
      khataNumber: createField('889', 0.94),
      area: createField(5.20, 0.95),
      areaUnit: createField('Acres', 0.95),
      village: createField('Mandi', 0.97),
      tehsil: createField('Sehore', 0.96),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.96),
      ownershipType: createField<OwnershipType>('Joint Ownership (संयुक्त)', 0.93),
      language: 'Hindi',
      confidenceScore: 95,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.1990, lng: 77.0540 },
    },
    {
      recordId: 'REC-MP-SEH-015',
      ownerName: createField('ग्राम पंचायत रामपुर (Gram Panchayat Rampur)', 0.96),
      fatherOrSpouseName: createField('शासकीय प्रतिनिधि (Govt Representative)', 0.95),
      surveyNumber: createField('1', 0.98),
      khasraNumber: createField('1', 0.98),
      khataNumber: createField('01', 0.96),
      area: createField(12.50, 0.97),
      areaUnit: createField('Acres', 0.98),
      village: createField('Rampur', 0.98),
      tehsil: createField('Sehore', 0.97),
      district: createField('Sehore', 0.99),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Government / Grazing (शासकीय/चरनोई)', 0.98),
      ownershipType: createField<OwnershipType>('Government Leased (पट्टा)', 0.97),
      language: 'Hindi',
      confidenceScore: 98,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.2080, lng: 77.0810 },
    },
    {
      recordId: 'REC-MP-SEH-016',
      ownerName: createField('राजेन्द्र प्रसाद (Rajendra Prasad)', 0.94),
      fatherOrSpouseName: createField('मिश्रीलाल (Mishrilal)', 0.92),
      surveyNumber: createField('630/4', 0.95),
      khasraNumber: createField('630/4', 0.95),
      khataNumber: createField('412', 0.91),
      area: createField(1.95, 0.93),
      areaUnit: createField('Acres', 0.95),
      village: createField('Brijisnagar', 0.96),
      tehsil: createField('Ichhawar', 0.95),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.94),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.92),
      language: 'Hindi',
      confidenceScore: 94,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.0120, lng: 77.0180 },
    },
    {
      recordId: 'REC-MP-SEH-017',
      ownerName: createField('दीपक कुमार जैन (Deepak Kumar Jain)', 0.95),
      fatherOrSpouseName: createField('नेमीचंद जैन (Nemichand Jain)', 0.94),
      surveyNumber: createField('77/3', 0.96),
      khasraNumber: createField('77/3', 0.96),
      khataNumber: createField('901', 0.93),
      area: createField(0.75, 0.94),
      areaUnit: createField('Acres', 0.96),
      village: createField('Pagara', 0.96),
      tehsil: createField('Ashta', 0.95),
      district: createField('Sehore', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Commercial (व्यावसायिक)', 0.95),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.93),
      language: 'Hindi',
      confidenceScore: 95,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.0210, lng: 76.7210 },
    },
    {
      recordId: 'REC-MP-BHP-018',
      ownerName: createField('Mohd. Tariq Khan', 0.96),
      fatherOrSpouseName: createField('Abdul Wahid Khan', 0.94),
      surveyNumber: createField('318/1', 0.97),
      khasraNumber: createField('318/1', 0.97),
      khataNumber: createField('625', 0.92),
      area: createField(1.25, 0.95),
      areaUnit: createField('Acres', 0.96),
      village: createField('Bairagarh', 0.97),
      tehsil: createField('Huzur', 0.97),
      district: createField('Bhopal', 0.99),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Residential (आवासीय)', 0.96),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.94),
      language: 'English',
      confidenceScore: 96,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.2780, lng: 77.3410 },
    },
    {
      recordId: 'REC-MP-VID-019',
      ownerName: createField('रघुवीर सिंह रघुवंशी (Raghuveer Singh)', 0.94),
      fatherOrSpouseName: createField('बलदेव सिंह (Baldev Singh)', 0.93),
      surveyNumber: createField('914/2', 0.95),
      khasraNumber: createField('914/2', 0.95),
      khataNumber: createField('144', 0.91),
      area: createField(3.80, 0.93),
      areaUnit: createField('Acres', 0.95),
      village: createField('Rangai', 0.96),
      tehsil: createField('Vidisha', 0.96),
      district: createField('Vidisha', 0.98),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.94),
      ownershipType: createField<OwnershipType>('Single Owner (एकल)', 0.92),
      language: 'Hindi',
      confidenceScore: 94,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 23.5410, lng: 77.8120 },
    },
    {
      recordId: 'REC-MP-IND-020',
      ownerName: createField('पंकज पाटीदार (Pankaj Patidar)', 0.96),
      fatherOrSpouseName: createField('जगदीश पाटीदार (Jagdish Patidar)', 0.95),
      surveyNumber: createField('1204', 0.97),
      khasraNumber: createField('1204', 0.97),
      khataNumber: createField('980', 0.94),
      area: createField(6.40, 0.96),
      areaUnit: createField('Acres', 0.96),
      village: createField('Rau', 0.97),
      tehsil: createField('Indore', 0.97),
      district: createField('Indore', 0.99),
      state: createField('Madhya Pradesh', 0.99),
      landClassification: createField<LandClassification>('Agricultural (कृषि)', 0.96),
      ownershipType: createField<OwnershipType>('Joint Ownership (संयुक्त)', 0.94),
      language: 'Hindi',
      confidenceScore: 96,
      validationStatus: 'passed',
      verificationStatus: 'verified',
      gisCoordinates: { lat: 22.6320, lng: 75.8110 },
    },
  ];

  const createdRecords = await LandRecord.insertMany(recordsData as any);
  console.log(` Created ${createdRecords.length} realistic Land Records.`);

  // 3. Seed 10 Documents
  const documentsData = [
    {
      documentId: 'DOC-MP-2026-001',
      originalName: 'khasra_sehore_rampur_124_3.pdf',
      fileUrl: '/samples/khasra_sample.png',
      fileType: 'application/pdf',
      fileSize: 2451000,
      documentType: 'Khasra',
      language: 'Hindi',
      state: 'Madhya Pradesh',
      district: 'Sehore',
      tehsil: 'Sehore',
      village: 'Rampur',
      status: 'completed',
      ocrConfidence: 96,
      ocrText: 'प्रारूप खसरा (अधिकार अभिलेख) - मध्य प्रदेश शासन\nग्राम: रामपुर | तहसील: सीहोर | जिला: सीहोर\nभूमि स्वामी: रमेश कुमार | पिता: सुरेश कुमार\nखसरा नं.: 124/3 | खाता संख्या: 458 | क्षेत्रफल: 2.45 एकड़\nभूमि का प्रकार: कृषि (दो फसली) | स्वामित्व: एकल कृषक',
      detectedLanguage: 'Hindi (Devanagari)',
      detectedScript: 'Devanagari',
      extractedRecordId: 'REC-MP-SEH-001',
      uploadedBy: 'Shri Manoj Patel',
    },
    {
      documentId: 'DOC-MP-2026-002',
      originalName: 'deed_conflict_rampur_124_3.jpg',
      fileUrl: '/samples/khasra_sample.png',
      fileType: 'image/jpeg',
      fileSize: 1840000,
      documentType: 'Jamabandi',
      language: 'Hindi',
      state: 'Madhya Pradesh',
      district: 'Sehore',
      tehsil: 'Sehore',
      village: 'Rampur',
      status: 'verification_pending',
      ocrConfidence: 92,
      ocrText: 'जमाबंदी नामांतरण पंजी\nग्राम: रामपुर | तहसील: सीहोर | जिला: सीहोर\nभूमि स्वामी: दिनेश चंद्र | पिता: रामप्रसाद\nखसरा नं.: 124/3 | खाता: 912 | क्षेत्रफल: 2.45 एकड़',
      detectedLanguage: 'Hindi (Devanagari)',
      detectedScript: 'Devanagari',
      extractedRecordId: 'REC-MP-SEH-002',
      uploadedBy: 'Shri Manoj Patel',
    },
    {
      documentId: 'DOC-MP-2026-003',
      originalName: 'parent_parcel_khasra_88.png',
      fileUrl: '/samples/khasra_sample.png',
      fileType: 'image/png',
      fileSize: 2190000,
      documentType: 'Khasra',
      language: 'Hindi',
      state: 'Madhya Pradesh',
      district: 'Sehore',
      tehsil: 'Sehore',
      village: 'Rampur',
      status: 'completed',
      ocrConfidence: 97,
      ocrText: 'खसरा मूल किता नंबर: 88 | कुल रकबा: 5.00 एकड़\nभूमि स्वामी: गोपाल दास आत्मज हरिराम',
      extractedRecordId: 'REC-MP-SEH-003',
      uploadedBy: 'Smt. Priya Sharma',
    },
    {
      documentId: 'DOC-MP-2026-004',
      originalName: 'subparcel_batankan_88_1.png',
      fileUrl: '/samples/khasra_sample.png',
      fileType: 'image/png',
      fileSize: 1980000,
      documentType: 'RoR',
      language: 'Hindi',
      state: 'Madhya Pradesh',
      district: 'Sehore',
      tehsil: 'Sehore',
      village: 'Rampur',
      status: 'completed',
      ocrConfidence: 95,
      ocrText: 'बटांकन खसरा नंबर 88/1 | रकबा: 3.20 एकड़ | हिस्सेदार: सुनील दास',
      extractedRecordId: 'REC-MP-SEH-004',
      uploadedBy: 'Smt. Priya Sharma',
    },
    {
      documentId: 'DOC-MP-2026-005',
      originalName: 'subparcel_batankan_88_2_excess.png',
      fileUrl: '/samples/khasra_sample.png',
      fileType: 'image/png',
      fileSize: 1950000,
      documentType: 'RoR',
      language: 'Hindi',
      state: 'Madhya Pradesh',
      district: 'Sehore',
      tehsil: 'Sehore',
      village: 'Rampur',
      status: 'verification_pending',
      ocrConfidence: 93,
      ocrText: 'बटांकन खसरा नंबर 88/2 | रकबा: 2.80 एकड़ | हिस्सेदार: मुकेश दास',
      extractedRecordId: 'REC-MP-SEH-005',
      uploadedBy: 'Smt. Priya Sharma',
    },
    {
      documentId: 'DOC-MP-2026-006',
      originalName: 'mutation_order_date_error_302.pdf',
      fileUrl: '/samples/khasra_sample.png',
      fileType: 'application/pdf',
      fileSize: 2100000,
      documentType: 'Mutation Record',
      language: 'Hindi',
      state: 'Madhya Pradesh',
      district: 'Sehore',
      tehsil: 'Sehore',
      village: 'Bilkisganj',
      status: 'verification_pending',
      ocrConfidence: 90,
      ocrText: 'नामांतरण पंजी आदेश क्रमांक M-2021-9981 दिनांक 10/03/2021\nपंजीकृत विक्रय विलेख क्र. REG-2022-4419 दिनांक 15/08/2022',
      extractedRecordId: 'REC-MP-SEH-006',
      uploadedBy: 'Shri Manoj Patel',
    },
    {
      documentId: 'DOC-MP-2026-007',
      originalName: 'noisy_handwritten_khasra_215.jpg',
      fileUrl: '/samples/khasra_sample.png',
      fileType: 'image/jpeg',
      fileSize: 1540000,
      documentType: 'Khasra',
      language: 'Hindi',
      state: 'Madhya Pradesh',
      district: 'Sehore',
      tehsil: 'Sehore',
      village: 'Shyampur',
      status: 'verification_pending',
      ocrConfidence: 62,
      ocrText: 'जीर्ण हस्तलिखित खसरा पंजी 215/? ... भूमि स्वामी कैलाश ना..थ ... रकबा 3.40(?)',
      extractedRecordId: 'REC-MP-SEH-007',
      uploadedBy: 'Shri Manoj Patel',
    },
    {
      documentId: 'DOC-MP-2026-008',
      originalName: 'registered_sale_deed_bhopal_45_1a.pdf',
      fileUrl: '/samples/khasra_sample.png',
      fileType: 'application/pdf',
      fileSize: 3100000,
      documentType: 'Sale/Registration Record',
      language: 'English',
      state: 'Madhya Pradesh',
      district: 'Bhopal',
      tehsil: 'Huzur',
      village: 'Kolar',
      status: 'completed',
      ocrConfidence: 98,
      ocrText: 'Registered Conveyance Deed - Plot No. 45/1A Kolar Road Bhopal\nOwner: Mrs. Anita Deshmukh | Valuation: Rs 45,00,000',
      extractedRecordId: 'REC-MP-BHP-008',
      uploadedBy: 'Ananya Deshmukh',
    },
    {
      documentId: 'DOC-MP-2026-009',
      originalName: 'cadastral_map_ratibad_712.pdf',
      fileUrl: '/samples/khasra_sample.png',
      fileType: 'application/pdf',
      fileSize: 4200000,
      documentType: 'Cadastral Map',
      language: 'Hindi',
      state: 'Madhya Pradesh',
      district: 'Bhopal',
      tehsil: 'Huzur',
      village: 'Ratibad',
      status: 'completed',
      ocrConfidence: 96,
      ocrText: 'नक्शा खसरा व तरमीम खाता 550 रकबा 4.20 एकड़ सत्यनारायण शर्मा',
      extractedRecordId: 'REC-MP-BHP-009',
      uploadedBy: 'Dr. Rajeshwar Verma, IAS',
    },
    {
      documentId: 'DOC-MP-2026-010',
      originalName: 'jamabandi_vidisha_108_2.pdf',
      fileUrl: '/samples/khasra_sample.png',
      fileType: 'application/pdf',
      fileSize: 2280000,
      documentType: 'Jamabandi',
      language: 'Hindi',
      state: 'Madhya Pradesh',
      district: 'Vidisha',
      tehsil: 'Vidisha',
      village: 'Gulabganj',
      status: 'completed',
      ocrConfidence: 94,
      ocrText: 'जमाबंदी अधिकार अभिलेख वर्ष 2024-25 भागवत प्रसाद ग्राम गुलाबगंज',
      extractedRecordId: 'REC-MP-VID-010',
      uploadedBy: 'Dr. Rajeshwar Verma, IAS',
    },
  ];

  await DocumentModel.insertMany(documentsData as any);
  console.log(` Created ${documentsData.length} indexed documents.`);

  // 4. Run Validation Engine to generate Validation Results for all records
  console.log('⚡ Running Validation Engine across all records to build diagnostics...');
  const allRecords = await LandRecord.find().lean();

  for (const rec of allRecords) {
    const existing = allRecords.filter((r) => r.recordId !== rec.recordId);
    const vResult = validationEngine.validateRecord(rec as any, { existingRecords: existing as any });
    await ValidationResultModel.create(vResult);
  }

  // 5. Create 5 Verification Tasks for problematic records
  const tasksData = [
    {
      taskId: 'TASK-MP-2026-001',
      recordId: 'REC-MP-SEH-002',
      documentId: 'DOC-MP-2026-002',
      village: 'Rampur',
      tehsil: 'Sehore',
      district: 'Sehore',
      ownerName: 'दिनेश चंद्र (Dinesh Chandra)',
      surveyNumber: '124/3',
      issueCount: 2,
      overallConfidence: 88,
      priority: 'urgent',
      status: 'pending',
      flagReasons: [
        'Survey No. 124/3 in Village Rampur is claimed by "दिनेश चंद्र", but previously registered under "रमेश कुमार" (Record REC-MP-SEH-001). Potential title collision detected.',
        'Ownership conflict requires mandatory SDM / Tehsildar human verification.',
      ],
    },
    {
      taskId: 'TASK-MP-2026-002',
      recordId: 'REC-MP-SEH-005',
      documentId: 'DOC-MP-2026-005',
      village: 'Rampur',
      tehsil: 'Sehore',
      district: 'Sehore',
      ownerName: 'मुकेश दास (Mukesh Das)',
      surveyNumber: '88/2',
      issueCount: 1,
      overallConfidence: 90,
      priority: 'urgent',
      status: 'pending',
      flagReasons: [
        'The sum of sub-parcels (3.20 + 2.80 = 6.00 Acres) exceeds parent parcel 88 (5.00 Acres). Area inflation detected.',
      ],
    },
    {
      taskId: 'TASK-MP-2026-003',
      recordId: 'REC-MP-SEH-006',
      documentId: 'DOC-MP-2026-006',
      village: 'Bilkisganj',
      tehsil: 'Sehore',
      district: 'Sehore',
      ownerName: 'महेंद्र सिंह (Mahendra Singh)',
      surveyNumber: '302/1',
      issueCount: 1,
      overallConfidence: 89,
      priority: 'medium',
      status: 'pending',
      flagReasons: [
        'Mutation was recorded on 2021-03-10 before the deed was registered on 2022-08-15. Chronological anomaly detected.',
      ],
    },
    {
      taskId: 'TASK-MP-2026-004',
      recordId: 'REC-MP-SEH-007',
      documentId: 'DOC-MP-2026-007',
      village: 'Shyampur',
      tehsil: 'Sehore',
      district: 'Sehore',
      ownerName: 'कैलाश ना..थ (Kailash N..th)',
      surveyNumber: '215/?',
      issueCount: 3,
      overallConfidence: 64,
      priority: 'high',
      status: 'pending',
      flagReasons: [
        'AI confidence for Owner Name is only 58%. Text is degraded or handwritten.',
        'AI confidence for Survey Number is only 61%.',
        'AI confidence for Area is only 62%.',
      ],
    },
    {
      taskId: 'TASK-MP-2026-005',
      recordId: 'REC-MP-SEH-001',
      documentId: 'DOC-MP-2026-001',
      village: 'Rampur',
      tehsil: 'Sehore',
      district: 'Sehore',
      ownerName: 'रमेश कुमार (Ramesh Kumar)',
      surveyNumber: '124/3',
      issueCount: 0,
      overallConfidence: 94,
      priority: 'low',
      status: 'verified',
      assignedOfficer: 'Shri Manoj Patel',
      resolvedAt: '2026-09-25T14:30:00Z',
      resolvedBy: 'Shri Manoj Patel',
      resolutionNotes: 'Matched with legacy revenue seal and approved.',
      flagReasons: ['Standard post-digitization verification audit.'],
    },
  ];

  await VerificationTaskModel.insertMany(tasksData as any);
  console.log(` Created ${tasksData.length} verification tasks.`);

  // 6. Seed 25+ Comprehensive Audit Logs
  const auditLogsData = [
    {
      logId: 'AUD-2026-001',
      recordId: 'REC-MP-SEH-001',
      documentId: 'DOC-MP-2026-001',
      action: 'DOCUMENT_UPLOADED',
      performedBy: { userId: createdUsers[2]._id.toString(), name: createdUsers[2].name, role: createdUsers[2].role, email: createdUsers[2].email },
      details: 'Scanned Khasra PDF uploaded for Rampur village.',
      ipAddress: '10.24.118.52',
      timestamp: '2026-09-25T10:15:00Z',
    },
    {
      logId: 'AUD-2026-002',
      recordId: 'REC-MP-SEH-001',
      documentId: 'DOC-MP-2026-001',
      action: 'OCR_COMPLETED',
      performedBy: { userId: 'sys-ocr', name: 'Bhoomi Setu AI Hybrid Indic-OCR', role: 'admin', email: 'ocr-engine@bhoomi.gov.in' },
      details: 'OCR processed 14 text blocks with 96% overall confidence.',
      ipAddress: '127.0.0.1',
      timestamp: '2026-09-25T10:15:04Z',
    },
    {
      logId: 'AUD-2026-003',
      recordId: 'REC-MP-SEH-001',
      documentId: 'DOC-MP-2026-001',
      action: 'FIELDS_EXTRACTED',
      performedBy: { userId: 'sys-ai', name: 'Bhoomi Setu AI Neural Entity Extractor', role: 'admin', email: 'ai-engine@bhoomi.gov.in' },
      details: 'Extracted structured fields for Owner: Ramesh Kumar, Survey: 124/3, Area: 2.45 Acres.',
      ipAddress: '127.0.0.1',
      timestamp: '2026-09-25T10:15:08Z',
    },
    {
      logId: 'AUD-2026-004',
      recordId: 'REC-MP-SEH-001',
      documentId: 'DOC-MP-2026-001',
      action: 'VALIDATION_PASSED',
      performedBy: { userId: 'sys-val', name: 'Rule-Based Validation Engine', role: 'admin', email: 'rules@bhoomi.gov.in' },
      details: 'Validation passed with 10/10 rules verified. Quality Score: 100/100.',
      ipAddress: '127.0.0.1',
      timestamp: '2026-09-25T10:15:10Z',
    },
    {
      logId: 'AUD-2026-005',
      recordId: 'REC-MP-SEH-001',
      documentId: 'DOC-MP-2026-001',
      action: 'RECORD_VERIFIED',
      performedBy: { userId: createdUsers[2]._id.toString(), name: createdUsers[2].name, role: createdUsers[2].role, email: createdUsers[2].email },
      details: 'Officer verified record against physical patwari register.',
      ipAddress: '10.24.118.52',
      timestamp: '2026-09-25T14:30:00Z',
    },
    {
      logId: 'AUD-2026-006',
      recordId: 'REC-MP-SEH-002',
      documentId: 'DOC-MP-2026-002',
      action: 'DOCUMENT_UPLOADED',
      performedBy: { userId: createdUsers[2]._id.toString(), name: createdUsers[2].name, role: createdUsers[2].role, email: createdUsers[2].email },
      details: 'Jamabandi register image uploaded.',
      ipAddress: '10.24.118.52',
      timestamp: '2026-09-26T09:00:00Z',
    },
    {
      logId: 'AUD-2026-007',
      recordId: 'REC-MP-SEH-002',
      documentId: 'DOC-MP-2026-002',
      action: 'VALIDATION_FAILED',
      performedBy: { userId: 'sys-val', name: 'Rule-Based Validation Engine', role: 'admin', email: 'rules@bhoomi.gov.in' },
      details: 'Critical validation failure: RULE_01_SURVEY_CONSISTENCY & RULE_08_OWNER_CONFLICT on Survey 124/3.',
      ipAddress: '127.0.0.1',
      timestamp: '2026-09-26T09:00:12Z',
    },
    {
      logId: 'AUD-2026-008',
      recordId: 'REC-MP-SEH-005',
      documentId: 'DOC-MP-2026-005',
      action: 'VALIDATION_FAILED',
      performedBy: { userId: 'sys-val', name: 'Rule-Based Validation Engine', role: 'admin', email: 'rules@bhoomi.gov.in' },
      details: 'Critical validation failure: RULE_02_AREA_CONSISTENCY. Sub-parcels sum 6.00 Acres > Parent 5.00 Acres.',
      ipAddress: '127.0.0.1',
      timestamp: '2026-09-26T11:20:00Z',
    },
    {
      logId: 'AUD-2026-009',
      recordId: 'REC-MP-SEH-007',
      documentId: 'DOC-MP-2026-007',
      action: 'FIELD_CORRECTED',
      performedBy: { userId: createdUsers[2]._id.toString(), name: createdUsers[2].name, role: createdUsers[2].role, email: createdUsers[2].email },
      fieldChanged: 'ownerName',
      oldValue: 'कैलाश ना..थ',
      newValue: 'कैलाश नाथ (Kailash Nath)',
      reason: 'Corrected OCR typo from original stamp margin',
      ipAddress: '10.24.118.52',
      timestamp: '2026-09-27T08:45:00Z',
    },
  ];

  await AuditLogModel.insertMany(auditLogsData as any);
  console.log(` Created ${auditLogsData.length} audit trail records.`);

  console.log('✅ Bhoomi Setu AI Database Seeding completed successfully!');
}

if (require.main === module) {
  connectDB()
    .then(seedDatabase)
    .then(() => disconnectDB())
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Seed error:', err);
      process.exit(1);
    });
}
